<?xml version="1.0"?>
<package format="3">
  <name>pal_transmissions</name>
  <version>1.0.0</version>
  <description>
    Open source ROS Control transmission for PAL Robots
  </description>
  <maintainer email="adria.roig@pal-robotics.com">Adria Roig</maintainer>
  <author email="adria.roig@pal-robotics.com">Adria Roig</author>
  
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>eigen3_cmake_module</buildtool_depend>
  
  <build_depend>rclcpp</build_depend>
  <build_depend>controller_interface</build_depend>
  <build_depend>hardware_interface</build_depend>
  <build_depend>pluginlib</build_depend>
  <build_depend>resource_retriever</build_depend>
  <build_depend>transmission_interface</build_depend>
  <build_depend>pal_logger</build_depend>

  <build_export_depend>rclcpp</build_export_depend>
  <build_export_depend>controller_interface</build_export_depend>
  <build_export_depend>hardware_interface</build_export_depend>
  <build_export_depend>pluginlib</build_export_depend>
  <build_export_depend>resource_retriever</build_export_depend>
  <build_export_depend>transmission_interface</build_export_depend>
  <build_export_depend>pal_logger</build_export_depend>

  <buildtool_export_depend>eigen3_cmake_module</buildtool_export_depend>

  <test_depend>ament_cmake_gmock</test_depend>
  <test_depend>ros2_control_test_assets</test_depend>


<export>
  <build_type>ament_cmake</build_type>
</export>


</package>
